name: Générer PDF du README

on:
  push:
    paths:
      - README.md
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Convertir README.md en PDF avec markdown-pdf-action
        uses: BlueHatbRit/markdown-pdf-action@v1.2.0
        with:
          input_path: README.md
          output_path: README.pdf

      - name: Upload du PDF en tant qu'artefact
        uses: actions/upload-artifact@v4
        with:
          name: README PDF
          path: README.pdf

      - name: Upload du PDF à la release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: README.pdf
