name: Générer PDF du README

on:
  push:
    paths:
      - README.md
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer les dépendances
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Convertir README.md en PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: .
          output_dir: .
          input_file: README.md
          build_html: false

      - name: Upload du PDF en tant qu’artefact
        uses: actions/upload-artifact@v4
        with:
          name: README PDF
          path: README.pdf

      - name: Upload du PDF à la release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: README.pdf
