name: Générer PDF pour tous les fichiers Markdown

on:
  push:
    paths:
      - '**.md'
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installer md-to-pdf
        run: npm install -g md-to-pdf

      - name: Générer les PDF pour tous les fichiers .md
        run: |
          for file in *.md; do
            [ -e "$file" ] || continue
            md-to-pdf "$file" --stylesheet github-markdown.css --body-class=markdown-body
          done

      - name: Upload des PDF en tant qu'artefacts
        uses: actions/upload-artifact@v4
        with:
          name: PDFs Markdown
          path: '*.pdf'

      - name: Upload des PDF à la release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: '*.pdf'
